<?php

return array(
"Abandono"=>"El acto de desatender a un niño en condiciones en las que no existan garantías que preserven su salud, su seguridad o su bienestar (ver también \"Renuncia a la guarda\"). El abandono puede ser voluntario o forzado. Por lo general, no se conoce la familia de origen.",
"Adopción"=>"La delegación legal y definitiva del ejercicio de la responsabilidad parental a personas que no sean los padres biológicos del menor, con lo cual se crea una nueva relación filial. En consecuencia, la adopción no constituye una forma de acogimiento alternativo (para niños privados del cuidado parental), de tal manera que, una vez que se pone al niño bajo la custodia efectiva de los padres adoptivos en virtud de una sentencia firme de adopción, ya no rigen las Directrices sobre las modalidades alternativas de cuidado de los niños. No obstante, las Directrices sí se aplican al período de preadopción o adopción a prueba.",
"Cuidado"=>"Una solución formal o informal por la cual el niño es acogido, como mínimo, una noche fuera del hogar parental, ya sea por decisión de una autoridad judicial o administrativa o un órgano debidamente autorizado o por iniciativa del niño, uno o los dos padres o los cuidadores principales o bien espontáneamente por un proveedor de servicios de acogimiento ante la ausencia de los padres (Better Care Network Toolkit).",
"Acogimiento alternativo"=>"Una solución formal o informal por la cual el niño es acogido, como mínimo, una noche fuera del hogar parental, ya sea por decisión de una autoridad judicial o administrativa o un órgano debidamente autorizado o por iniciativa del niño, uno o los dos padres o los cuidadores principales o bien espontáneamente por un proveedor de servicios de acogimiento ante la ausencia de los padres (Better Care Network Toolkit).",
"Proveedores de acogimiento autorizados y no autorizados"=>"Todos los proveedores de acogimiento deben someterse a una evaluación por parte de un organismo gubernamental o una entidad autorizada por el gobierno con el fin de determinar si la calidad del cuidado es, como mínimo, adecuada. Los proveedores de cuidado que cumplen los requisitos pasan a ser proveedores autorizados. Aquellos que no solicitan autorización o que no reúnen los requisitos son proveedores de cuidado no autorizados.",
"Interés superior del niño"=>"\"El niño tiene derecho a que su 'interés superior' sea tenido en cuenta como una 'consideración primordial' cada vez que las 'instituciones públicas o privadas de bienestar social, los tribunales, las autoridades administrativas o los órganos legislativos' tomen decisiones concernientes al niño\" (Avanzando en la implementación, pág. 25 y CDN Artículo 3.1).",
"Cuidador"=>"Persona con la que vive el niño y que lo cuida a diario. También cumple funciones parentales, estén presentes o no los padres biológicos. Puede ser la madre, el padre u otro integrante de la familia, como un abuelo o hermano mayor. Comprende soluciones informales en las que el cuidador no tiene una responsabilidad jurídica (Better Care Network Toolkit).",
"Plan de acogimiento"=>"Documento escrito que identifica los objetivos del período de acogimiento alternativo del niño, las metas del acogimiento en particular, las acciones necesarias para lograr los objetivos establecidos y un calendario de acciones y evaluaciones de ese acogimiento.",
"Proveedor de servicios de acogimiento"=>"Organización o persona que posee o administra uno o más centros de acogida.",
"Gestión del caso"=>"Proceso que consiste en prestar asistencia a un menor y a su familia brindando apoyo y derivaciones a otros servicios prestados por profesionales como trabajadores sociales, entre otros.",
"Cuidado infantil"=>"Situación en la que un niño es acogido diaria o frecuentemente en el marco de un servicio provisto por un organismo estatal o no estatal o un cuidador profesional.",
"Guardería"=>"Situación en la que un niño es acogido diaria o frecuentemente en el marco de un servicio provisto por un organismo estatal o no estatal o un cuidador profesional.",
"Protección infantil"=>"Prevención de la violencia, la explotación y el maltrato infantil y respuestas a esos agravios.",
"Sistema de protección infantil"=>"La suma de leyes, políticas, estructuras, mecanismos y servicios necesarios para prevenir y responder al maltrato y la explotación infantiles, así como a otras violaciones de los derechos fundamentales de la infancia.",
"Niños sin cuidado parental"=>"\"Todos los niños que durante la noche no estén al cuidado\" (Directrices, párr. 29a) ya sea de ambos padres o de uno de ellos como resultado de \"la incapacidad o falta de voluntad general de los padres para cumplir los deberes que les incumben en relación con la guarda de su hijo\" (Directrices, párr. 30. c).",
"Procesos de queja"=>"Mecanismos de queja formal para que los niños en acogimiento alternativo puedan denunciar violaciones a sus derechos, como maltrato y explotación.",
"Castigo corporal"=>"Castigo corporal (y otras formas de castigo crueles o degradantes). El Comité de los Derechos del Niño define el castigo \"corporal\" o \"físico\" como todo castigo en el que se utilice la fuerza física y que tenga por objeto causar cierto grado de dolor o malestar, aunque sea leve. Este tipo de castigo casi siempre consiste en golpear, pero también puede consistir, entre otras cosas, en dar puntapiés, zarandear o empujar a los niños, arañarlos, pellizcarlos, morderlos, tirarles del pelo o de las orejas, obligarlos a ponerse en posturas incómodas, producirles quemaduras u obligarlos a ingerir alimentos u otros productos. En opinión del Comité, el castigo corporal siempre es degradante. Además, existen otras formas de castigo que no son físicas, pero que son igualmente crueles y degradantes y, de este modo, incompatibles con la Convención sobre los Derechos del Niño. Entre estas se cuentan, por ejemplo, los castigos en que se menosprecia, se humilla, se denigra, se convierte en chivo expiatorio, se amenaza, se asusta o se ridiculiza al niño.

Versión abreviada de la definición proporcionada por el Comité de los Derechos del Niño (2006) COMENTARIO GENERAL Nº 8 (2006) CRC / C / GC / - El derecho del niño a la protección contra el castigo corporal y otras formas crueles o degradantes de castigo (artículos 19, 28 (2) etc.).

El párr. 96 de las Directrices también subraya que las medidas de aislamiento e incomunicación se consideran como tortura o tratos crueles, inhumanos o degradantes y deben quedar prohibidas estrictamente de conformidad con las normas internacionales de  derechos humanos.",
"Discapacidad"=>"\"Las personas con discapacidad incluyen a aquellas que tengan deficiencias físicas, mentales, intelectuales o sensoriales a largo plazo que, al interactuar con diversas barreras, puedan impedir su participación plena y efectiva en la sociedad, en igualdad de condiciones con las demás\" (Convención sobre los Derechos de las Personas con Discapacidad, artículo 1).",
"Acogimiento de emergencia"=>"El ingreso necesario de un niño en acogimiento alternativo con escasa antelación, con muy poco tiempo para prepararlo o para considerar de forma inmediata otras opciones que podrían corresponderse mejor con su interés superior.",
"Situaciones de emergencia"=>"Condiciones resultantes de \"desastres naturales o causados por el hombre, incluidos los conflictos armados con o sin carácter internacional y la ocupación extranjera\". (Directrices, párr. 153)",
"Organizaciones confesionales"=>"Organizaciones no gubernamentales cuyos fines y valores emanan explícitamente de una creencia religiosa.",
"Apoyo para la familia"=>"Políticas, servicios y programas diseñados para ayudar al niño a permanecer con su familia de origen o regresar a ella, mediante la prestación de apoyo práctico, social o emocional a los padres, a la familia en su conjunto o a hogares encabezados por niños. ",
"Organización con fines de lucro"=>"Organización cuyo fin es obtener un excedente económico, retenido por sus propietarios o accionistas.",
"Acogimiento alternativo formal"=>"\"Todo acogimiento en un entorno familiar que haya sido ordenado por la autoridad judicial o un órgano administrativo competente y todo acogimiento en un entorno residencial, incluidos los centros de acogida privados, resultante o no de medidas judiciales o administrativas\". (Directrices, párr. 29. b. ii)",
"Cuidadores formales"=>"Personal de acogimiento residencial (sin contar el personal auxiliar) y cuidadores de hogares de guarda aprobados, entre los que se cuentan los familiares que actúan como cuidadores formales, reconocidos por el sistema de acogimiento alternativo.",
"Cuidadores formales"=>"Todo acogimiento en un entorno doméstico de una familia que ha sido ordenado por una autoridad judicial o un organismo administrativo competente (extraído de las Directrices, párrs. 29.b. ii. y 29. c. ii.). El acogimiento en hogares de guarda y el acogimiento formal por familiares son dos tipos de acogimiento formal en entorno familiar.",
"Acogimiento en hogares de guarda"=>"\"Los supuestos en que una autoridad competente confía el niño a efectos de acogimiento alternativo al entorno doméstico de una familia distinta de su propia familia, que ha sido seleccionada, declarada idónea, aprobada y supervisada para ejercer ese acogimiento\" (Directrices, párr. 29. c. ii.).",
"Prevención del ingreso a las modalidades alternativas de acogimiento"=>"La evaluación sistemática, la revisión rigurosa y el proceso compartido de toma de decisiones por parte de organismos autorizados, con el fin de velar por que un niño ingrese en acogimiento alternativo solamente cuando sea necesario (Avanzando en la implementación, pág. 69).",
"Tutela"=>"Solución en virtud de la cual un tribunal u otro organismo judicial delega el ejercicio de numerosos derechos y responsabilidades parentales de los padres originales de un niño a otra persona o entidad, de forma temporal o por lo que resta del período de la niñez. El cuidado cotidiano del niño puede estar o no a cargo del tutor.",
"Estado de salud"=>"Condiciones de salud física o mental que afectan al niño.",
"Acogimiento alternativo informal"=>"\"Toda solución privada adoptada en un entorno familiar, en virtud de la cual el cuidado del niño es asumido con carácter permanente o indefinido por parientes o allegados (acogimiento informal por familiares) o por otras personas a título particular, por iniciativa del niño, de cualquiera de sus padres o de otra persona sin que esa solución haya sido ordenada por un órgano judicial o administrativo o por una entidad debidamente acreditada\" (Directrices, párr. 29. b. i.).",
"Inspecciones"=>"Visitas con y sin previo aviso por parte de personal autorizado y calificado para evaluar el cumplimiento de las normas pertinentes por parte de los proveedores de acogimiento que deberían incluir \"la observación del personal y los niños y entrevistas con ellos\" (Directrices, párrs. 128 y 129).",
"Instituciones"=>"Las Directrices no definen 'instituciones', sino una mención en el párr. 23 en que los iguala con \"Grandes\" centros de acogida residencial. El Grupo de trabajo de ONG sobre niños sin cuidado parental ha propuesto las siguientes características básicas para distinguir el acogimiento institucional de otras formas de acogimiento residencial: ‘Establecimientos de acogimiento residencial donde se cuida a los niños en cualquier centro de acogida público o privado, con cuidadores contratados o voluntarios que trabajan con horarios fijos o por turnos, y que funciona como alojamiento colectivo con amplia capacidad.’ El Grupo de Trabajo también subrayó ‘que es principalmente la “naturaleza del régimen de atención,” como si es familiar, si los cuidadores se encuentran en un entorno familiar o si el personal trabaja en turnos, o si existe una relación baja del cuidador por niño, que distingue el acogimiento institucional de otras formas de acogimiento residencial, en lugar de depender únicamente del tamaño. Si bien el tamaño suele ser un indicador de un entorno institucional, el establecimiento de un pequeño centro de acogimiento puede ser aún institucional.’ (Identifying Basic Characteristics of Formal Alternative Care Settings for Children, documento de debate del grupo de trabajo de ONG sobre niños sin cuidado parental, Ginebra, 2012, pp. 14-15).",
"ONG internacional"=>"Organismo no gubernamental sin fines de lucro que opera en más de un país.",
"Internados"=>"Una escuela que ofrece acogimiento residencial para algunos o todos sus alumnos a tiempo completo o parcial durante el período de tiempo. En algunos contextos, los internados pueden considerarse instituciones si los niños se colocan allí principalmente con fines de cuidado, como una alternativa a un orfanato o un hogar de niños, y que no tienen un alojamiento alternativo fuera del horario de clases. (Better Care Network Toolkit). Estos pueden incluir diferentes tipos de instituciones que brindan educación y atención, como instalaciones educativas para niños con necesidades especiales o escuelas auxiliares para niños con discapacidades.",
"Kafala"=>"Una modalidad de acogimiento familiar utilizado en sociedades islámicas que no implica cambio en el parentesco, pero que permite que un niño con el que no exista lazo de parentesco o de padres desconocidos reciba acogimiento, protección jurídica y una herencia (Better Care Network Toolkit).",
"Egreso del acogimiento"=>"Acto por el cual un niño se retira del sistema de acogimiento alternativo formal para reunirse con su familia, ser entregado en acogimiento por familiares o a una familia adoptiva, o tras haber cumplido la edad máxima para permanecer en el sistema de acogimiento.",
"Gobierno local"=>"Organismos públicos responsables de prestar servicios para la infancia a nivel subnacional (municipalidades, comunas, condados y autoridades locales, por ejemplo) conforme a los requerimientos establecidos por una autoridad de mayor jerarquía (v. también \"gobierno provincial\").",
"Gobierno nacional"=>"El principal órgano responsable de la formulación de leyes, de las finanzas y de los servicios dirigidos a todo un país (Estado-nación).",
"ONG nacional"=>"Organismo no gubernamental sin fines de lucro que opera en un solo país, ya sea en todo el territorio o parte de él. Las ONG también se denominan organizaciones voluntarias u organizaciones de beneficencia.",
"Normas nacionales"=>"Normas mínimas aprobadas para la prestación de servicios de acogimiento que deben cumplir todos los proveedores de esos servicios y su personal, y que se utilizan como parámetro para controlar esa prestación a través de inspecciones y otros medios.",
"Auxiliares en trabajo social"=>"Personal supervisado por profesionales, particularmente en situaciones en las que los sistemas y los servicios no disponen de suficiente personal profesional.",
"Permanencia"=>"La \"permanencia\" hace alusión a la reintegración final de un niño en su familia o bien a su entrega en un acogimiento formal de tipo familiar o en adopción en circunstancias que se consideren estables a largo plazo.",
"Acogimientos permanentes"=>"Los acogimientos permanentes son aquellos cuya duración prevista abarca lo que resta de la niñez y quizá los primeros años de la adultez de una persona.",
"Entrega (en acogimiento)"=>"Proceso que consiste en disponer que un niño ingrese en acogimiento alternativo formal y/o en el entorno en el cual se proporciona este tipo de servicio. Tiene lugar cuando un tribunal o una autoridad equivalente con validez jurídica (p. ej., comisión para la infancia) determina que el niño debe ingresar en una modalidad alternativa de acogimiento. Los padres y el menor no pueden impedir el ingreso sin recibir una sanción, aunque es posible que tengan derecho a apelación.",
"Cualitativo"=>"Fuentes de pruebas fundadas en encuestas de opinión, criterios y experiencias de las personas concernidas.",
"Cuantitativo"=>"Fuentes de pruebas expresadas en magnitudes numéricas (estadísticas).",
"Registro"=>"Proceso formal en virtud del cual a cada proveedor potencial o efectivo de servicios de acogimiento se le exige cursar notificaciones a un organismo gubernamental específico o a un organismo autorizado por el gobierno sobre su actividad o proporcionar pruebas del cumplimiento de las normas establecidas en materia de acogimiento.",
"Reintegración"=>"Procesos que apuntan a que el niño o joven pueda readaptarse a la vida con su familia y en su comunidad de origen tras haber pasado por el acogimiento alternativo. ",
"Reinserción"=>"Procesos que apuntan a que el niño o joven pueda readaptarse a la vida con su familia y en su comunidad de origen tras haber pasado por el acogimiento alternativo. ",
"Renuncia a la guarda"=>"Acto en virtud del cual un niño es entregado deliberadamente por parte de su familia al cuidado de un tercero, ya sea que ese acogimiento se prevea como temporal o como permanente (v. también \"Abandono\").",
"Remuneración"=>"Término general que indica el pago de dinero a cuidadores. Con relación al acogimiento residencial, se refiere a lo que gana el personal. Respecto del acogimiento en hogares de guarda, la remuneración normalmente se ha limitado a la compensación por los gastos de alimentación, vestimenta, educación, atención de salud y recreación del niño. En algunos casos, también incluye un salario, sueldo o pago a los cuidadores.",
"Acogimiento residencial"=>"\"Acogimiento ejercido en cualquier entorno colectivo no familiar, como los lugares seguros para la atención de emergencia, los centros de tránsito en casos de emergencia y todos los demás centros de acogimiento residencial a plazo corto y largo, incluidos los hogares funcionales\" (Directrices, párr. 29.c.iv.).",
"Niños separados"=>"Niños que han sido \"separados de ambos progenitores, o de su previo cuidador por ley o costumbre, pero no necesariamente de otros parientes\" (Directrices del ACNUR para la determinación del interés superior del niño, pág. 8).",
"Acogimientos a corto, mediano y largo plazo"=>"Es habitual definir la duración planificada o real del acogimiento de un niño en función de estas tres amplias categorías, si bien las definiciones varían. Normalmente, el corto plazo comprende unos meses, el largo plazo, varios años y el mediano plazo es un período intermedio entre las dos primeras categorías.",
"Trabajadores sociales"=>"Profesionales debidamente calificados según criterios profesionales que prestan servicios tales como apoyo a la familia, asesoramiento sobre la admisión y la estadía de niños en acogimiento alternativo, y asistencia a quienes egresan del acogimiento alternativo. ",
"Transición"=>"Las etapas y los procesos que ocurren cuando un niño egresa del sistema de acogimiento alternativo formal; p. ej., la preparación del niño y los miembros correspondientes de la familia, además de otras personas significativas; ayuda para la reinserción o el egreso; y la disponibilidad continua de apoyo tras el egreso.",
"Niños \"no acompañados\""=>"Niños \"que han sido separados, tanto de sus progenitores como del resto de sus parientes y que no se hallen al cuidado de un adulto que, por ley o costumbre, sea el responsable de ello\" (Directrices de la ACNUR para la determinación del interés superior del niño, pág. 8).",
"Verificación de antecedentes del personal y de los cuidadores"=>"Evaluación de la idoneidad de solicitantes de empleo para entornos de acogimiento alternativo formal por medio de la obtención de certificados médicos, referencias personales y la verificación de antecedentes penales, por ejemplo.",
"Ingreso voluntario"=>"Ingreso en una modalidad alternativa de cuidado formal con el consentimiento de los padres, tutores o el niño en cuestión.",
/**
 * References
 */
"REF001"=>"<p><b>FCI:</b> Indicador 4 (central), pág. 12</p>",
"REF002"=>"<p><b>FCI:</b> Indicador 8, pág. 16; indicador 13, pág. 21</p>",
"REF003"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF004"=>"<p><b>FCI:</b> Indicador 4 (central), pág. 12</p>",
"REF005"=>"<p><b>FCI:</b> Indicador 3 (central), pág. 11</p>",
"REF006"=>"<p><b>Directrices:</b> 6, 7, 40, 49, 57, 64, 65, 67, 94, 98, 99, 104, 132<br>
<b>Avanzando en la implementación:</b> \"Las Directrices se sustentan en el compromiso con el derecho de los niños a ser escuchados respecto de los asuntos que los afectan, de conformidad con el Art. 12 de la Convención sobre los Derechos del Niño (CDN). Este es un Principio General de las Directrices que debería reflejarse en todas las políticas y prácticas relacionadas con las modalidades alternativas de cuidado\" (pág. 27);<br>
<b>FCI:</b> Indicador 7, pág. 15; indicador 9, pág. 17; indicador 13, pág. 21; indicador 14, pág. 22; Herramienta de análisis de políticas 1; Herramienta de análisis de políticas 2.</p>",
"REF007"=>"<p><b>Directrices:</b> 23<br>
<b>Avanzando en la implementación:</b> \"... las Directrices optaron (...) por apelar a cada Estado a que elabore su propia estrategia para la desinstitucionalización gradual de sus sistemas de modalidades alternativas de cuidado, en lugar de proponer una prohibición rotunda de las instituciones. (...) la prioridad debería ser la prevención de la futura necesidad y del recurso al acogimiento alternativo y el desarrollo de una gama de opciones no institucionales cuando tal acogimiento sea necesario. Se debe prestar suma atención a la inclusión plena de los niños con discapacidad y otras necesidades especiales dentro de la estrategia de cada uno de los Estados; en la práctica, generalmente han sido los últimos en beneficiarse\" (pág. 44).</p>",
"REF008"=>"<p><b>Directrices:</b> 71, 84, 87, 89, 90, 106, 107, 113-117<br>
<b>Avanzando en la implementación:</b> \"El garantizar un reclutamiento, una selección, una capacitación, un empleo, una supervisión, un apoyo y un registro de los cuidadores que sean de alta calidad (§ 71) ayuda a asegurar que las personas que cuiden de niños tengan las habilidades, los conocimientos, las cualidades y los valores exigidos para satisfacer de manera efectiva la amplia variedad de necesidades de los niños bajo su cuidado\" (pág. 91).</p>",
"REF009"=>"<p><b>FCI:</b> Indicador 13, pág. 21; Herramienta de análisis de políticas 1 P1</p>",
"REF010"=>"<p><b>Directrices:</b> 32, 32, 33, 34, 35, 36, 37, 38<br>
<b>Avanzando en la implementación:</b> La prevención secundaria \"está enfocada en ciertos individuos y familias (y a veces grupos) que son identificados o se declaran a sí mismos como vulnerables, y para los cuales, debido a diversos motivos, las medidas de prevención primaria han resultado inadecuadas\" (pág. 54).</p>",
"REF011"=>"<p><b>FCI:</b> Indicador 11, pág. 19</p>",
"REF012"=>"<p><b>Directrices:</b> 9, 10, 34b, 38<br>
<b>Avanzando en la implementación:</b> \"La política y los servicios nacionales deberían proporcionar apoyo a los niños, sus familias y cuidadores para prevenir que los niños con discapacidad y otras necesidades especiales sean acogidos en modalidades alternativas de cuidado en aquellos casos en los que podrían vivir con sus familias\". Ver \"Implicancias para la elaboración de políticas: El apoyo a los derechos y las necesidades de los niños con discapacidad y otras necesidades especiales\", p. 36.</p>",
"REF013"=>"<p><b>Directrices:</b> 8<br>
<b>Avanzando en la implementación:</b> Las Directrices (§8) destacan la importancia de \"marcos nacionales para el apoyo, la protección y el cuidado de los niños\". Ver \"Implicancias para la elaboración de políticas: La prestación de un marco político para las modalidades alternativas de cuidado\" (pág. 48).<br>
<b>FCI:</b> Indicador 13, pág. 21; Herramienta de análisis de políticas 1</p>",
"REF014"=>"<p>CDN: Artículo 19 1. \"Los Estados Partes adoptarán todas las medidas legislativas, administrativas, sociales y educativas apropiadas para proteger al niño contra toda forma de perjuicio o abuso físico o mental, descuido o trato negligente, malos tratos o explotación, incluido el abuso sexual, mientras el niño se encuentre bajo la custodia de los padres, de un representante legal o de cualquier otra persona que lo tenga a su cargo\".</p>",
"REF015"=>"<p><b>Directrices:</b> 6, 7, 40, 49, 57, 64, 65, 67, 94, 98, 99, 104, 132<br>
<b>Avanzando en la implementación:</b> \"Las Directrices se sustentan en el compromiso con el derecho de los niños a ser escuchados respecto de los asuntos que los afectan, de conformidad con el Art. 12 de la CDN. Este es un Principio General de las Directrices que debería reflejarse en todas las políticas y prácticas relacionadas con las modalidades alternativas de cuidado\". Ver \"La participación de los niños y jóvenes en la toma de decisiones y los entornos de modalidades alternativas de cuidado\" (págs. 27 y 29).</p>",
"REF016"=>"<p><b>FCI:</b> Indicador 13, pág. 21; Herramienta de análisis de políticas 1</p>",
"REF017"=>"<p><b>Directrices:</b> 20, 24, 25, 108<br>
<b>Avanzando en la implementación:</b> \"Las Directrices reconocen que cada Estado tendrá diferentes condiciones económicas, pero ponen el énfasis en que cada Estado debería proporcionar los recursos financieros para las modalidades alternativas de cuidado en la 'medida de los recursos disponibles'\" (pág. 108).</p>",
"REF018"=>"<p><b>FCI:</b> Indicador 13, pág. 21; Herramienta de análisis de políticas 1 P1.7, P2.4</p>",
"REF019"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF020"=>"<p><b>Directrices:</b> 19, 21, 54, 55, 57, 69<br>
<b>Avanzando en la implementación:</b> \"La prevención del ingreso a las modalidades alternativas de cuidado implica un proceso sistemático y reconocido. En primer lugar, para determinar si el niño debe ser acogido en un entorno de acogimiento alternativo o no. Luego, para canalizar al niño y a su familia a modalidades adecuadas de apoyo familiar y otros servicios. Finalmente, para decidir cuál es la modalidad alternativa de cuidado de la gama disponible que se corresponde mejor a la situación particular del niño\" (pág. 69); <br>
V. \"Prevención del ingreso a las modalidades alternativas de acogimiento: El desarrollo de procedimientos para revisar las canalizaciones, evaluar la necesidad y autorizar el acogimiento\", págs. 69 y 70.</p>",
"REF021"=>"<p><b>FCI:</b> Indicador 8, pág. 16<br>
Convención sobre los Derechos del Niño de las Naciones Unidas (CDN): Comentario general n.o 14 (2013) sobre el derecho del niño a que su interés  superior sea una consideración primordial (art. 3, párr. 1) </p>",
"REF022"=>"<p><b>FCI:</b> Indicador 8, pág. 16</p>",
"REF023"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF024"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF025"=>"<p><b>Directrices:</b> &nbsp;47. Toda decisión sobre la remoción de la guarda de un niño contra la voluntad de  sus padres debe ser adoptada por la autoridad competente, de conformidad con las  leyes y procedimientos aplicables y estar sujeta a revisión judicial, garantizándose a  los padres el derecho de recurso y el acceso a asistencia letrada adecuada.<br>
<b>Avanzando en la implementación:</b> \"La 'participación del niño' está inevitablemente conectada con la consulta a la familia del niño, su representante designado, y/u otras personas importantes y de confianza para él. Este punto es enfatizado frecuentemente en las Directrices\" (pág. 27).<br>
<b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21<br>
CDN: Artículo 9 1. Los Estados Partes velarán por que el niño no sea separado de sus padres contra la voluntad de éstos, excepto cuando, a reserva de revisión judicial, las autoridades competentes determinen, de conformidad con la ley y los procedimientos aplicables, que tal separación es necesaria en el interés superior del niño. Tal determinación puede ser necesaria en casos particulares, por ejemplo, en los casos en que el niño sea objeto de maltrato o descuido por parte de sus padres o cuando éstos viven separados y debe adoptarse una decisión acerca del lugar de residencia del niño.</p>",
"REF026"=>"<p><b>Directrices:</b> 80, 95<br>
<b>Avanzando en la implementación:</b> \"Las Directrices prestan una atención específica a la prevención de la estigmatización de los niños en entornos de acogimiento alternativo\" (pág. 86).</p>",
"REF027"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF028"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF029"=>"<p><b>Directrices:</b> 17<br>
<b>Avanzando en la implementación:</b> \"Como regla general, los hermanos y hermanas no deberían ser separados en las modalidades alternativas de cuidado, salvo que existan razones imperiosas para hacerlo. Estas razones siempre deben cumplir con el interés superior de cualquiera de los niños involucrados (§ 17)\" (pág. 39).</p>",
"REF030"=>"<p><b>Directrices:</b> 64, 65, 66<br>
<b>Avanzando en la implementación:</b> La toma de decisiones \"(...) Debería suponer la plena consulta del niño en todas las fases del  proceso, de forma adecuada a su desarrollo evolutivo, y de sus padres o tutores  legales\". (Directrices, párr. 57). <br>
<b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF031"=>"<p><b>Directrices:</b> 19, 57, 58, 59, 60<br>
<b>Avanzando en la implementación:</b> \"La prevención del ingreso a las modalidades alternativas de cuidado implica un proceso sistemático y reconocido. En primer lugar, para determinar si el niño debe ser acogido en un entorno de acogimiento alternativo o no. Luego, para canalizar al niño y a su familia a modalidades adecuadas de apoyo familiar y otros servicios. Finalmente, para decidir cuál es la modalidad alternativa de cuidado de la gama disponible que se corresponde mejor a la situación particular del niño\" (pág. 69).</p>",
"REF032"=>"<p><b>FCI:</b> Indicador 9, pág. 17; indicador 13, pág. 21; Herramienta de análisis de políticas 1 P. 1.8</p>",
"REF033"=>"<p><b>Directrices:</b> 67<br>
\"Los Estados deberían garantizar el derecho de todo niño en acogimiento temporal a la revisión periódica y minuciosa ––preferiblemente cada tres meses por lo menos— de la idoneidad del cuidado y tratamiento que se le da, teniendo en cuenta sobre todo su desarrollo personal y cualquier variación de sus necesidades, los cambios en su entorno familiar y si, en vista de lo anterior, la modalidad de acogimiento sigue siendo necesaria y adecuada. La revisión debería estar a cargo de personas debidamente calificadas y habilitadas e implicar plenamente al niño y a todas las personas importantes en su vida\".<br>
<b>FCI:</b> Indicador 9, pág. 17</p>",
"REF034"=>"<p><b>FCI:</b> Indicador 9, pág. 17; indicador 13, pág. 21; Herramienta de análisis de políticas 1 - 3. 4</p>",
"REF035"=>"<p><b>Directrices:</b> 59<br>
\"El primer informe y las revisiones consiguientes deberían utilizarse como herramientas esenciales para las decisiones de planificación desde el momento de su aceptación por las autoridades competentes en adelante, con miras, en particular, a evitar toda perturbación indebida y decisiones contradictorias\".<br>
<b>FCI:</b> Indicador 7, pág. 15</p>",
"REF036"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF037"=>"<p><b>Directrices:</b> La preparación para el egreso de la modalidad  alternativa de cuidado y el apoyo en el período posterior  al acogimiento, párr. 131-136; \"La promoción de una reintegración sostenible de los niños a su familia desde el entorno de una modalidad alternativa de cuidado\" (2.a, 3, 14-15, 49-52, 60, 123, 166-167<br>
<b>Avanzando en la implementación:</b> \"Además de resaltar la necesidad de planear el retorno de un niño a su familia después de un período en acogimiento alternativo, las Directrices también abordan la preparación de la transición de los niños o jóvenes del sistema de acogimiento alternativo a la vida independiente (§ 131-136)\" (Avanzando en la implementación, pág. 101).<br>
V. \"La preparación para el egreso de la modalidad alternativa de cuidado y el apoyo en el período posterior al acogimiento\" y \"La promoción de una reintegración sostenible de los niños a su familia desde el entorno de una modalidad alternativa de cuidado\" en Avanzando en la implementación (págs. 101-103 y 64, respectivamente).</p>",
"REF038"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF039"=>"<p><b>Directrices:</b> 49<br>
\"Para preparar al niño y a la familia para su posible regreso a esta y para apoyar dicha reinserción, la situación del niño debería ser evaluada por una persona o un equipo debidamente designado que tenga acceso a asesoramiento multidisciplinario, en consulta con los distintos actores involucrados (el niño, la familia, el cuidador alternativo), a fin de decidir si la reintegración del niño en la familia es posible y redunda en favor del interés superior de este, qué medidas supondría y bajo la supervisión de quién\".</p>",
"REF040"=>"<p><b>Directrices:</b> 52<br>
\"Una vez decidida, la reintegración del niño en su familia debería concebirse como un proceso gradual y supervisado, acompañado de medidas de seguimiento y apoyo que tengan en cuenta la edad del niño, sus necesidades y desarrollo evolutivo y la causa de la separación\".<br>
<b>FCI:</b> Indicator 13, page 21</p>",
"REF041"=>"<p><b>Directrices:</b> 51<br>
\"El organismo competente debería elaborar, apoyar y vigilar los contactos regulares y apropiados entre el niño y su familia específicamente a los efectos de la reintegración\".</p>",
"REF042"=>"<p><b>Avanzando en la implementación:</b> \"Para ayudar a reducir los desafíos de la vida independiente, es muy importante que los jóvenes no sean desfavorecidos por ser 'expulsados' del acogimiento alternativo a una edad más temprana que aquella en la que sus pares habitualmente egresan del hogar familiar. En vez de ello, y si así lo desean, los niños y los jóvenes deberían ser autorizados, alentados y se les debe permitir mantener el contacto con, o permanecer bajo el cuidado, de los padres en los hogares de guarda o de otros cuidadores después de haber 'llegado a la edad de egreso' del sistema\" (Avanzando en la implementación, pág. 101).</p>",
"REF043"=>"<p><b>Directrices:</b> 131<br>
\"Las agencias y los centros de acogida deberían aplicar unas políticas claras y ejecutar los procedimientos acordados relativos a la conclusión programada o no de su trabajo con los niños con objeto de velar por la reinserción social o el seguimiento adecuados. Durante todo el período de acogida, dichas agencias y centros deberían fijarse sistemáticamente como objetivo la preparación del niño para asumir su independencia e integrarse plenamente en la comunidad, en particular su preparación para la vida cotidiana y el trato social, que se fomenta mediante la participación en la vida de la comunidad local\".</p>",
"REF044"=>"<p><b>Directrices:</b> 134<br>
\"La reinserción social debería prepararse lo más pronto posible en el entorno de acogida y, en cualquier caso, mucho antes de que el niño lo abandone\".</p>",
"REF045"=>"<p><b>Directrices:</b> 135<br>
\"Deberían ofrecerse oportunidades de educación y formación profesional continua, como parte de la preparación para la vida cotidiana de los jóvenes que se apresten a abandonar su entorno de acogida a fin de ayudarles a lograr la independencia económica y a generar sus propios ingresos\".</p>",
"REF046"=>"<p><b>Directrices:</b> 136<br>
\"También se debería proporcionar a los jóvenes cuyo acogimiento llegue a su fin y durante su reinserción social acceso a los servicios sociales, jurídicos y de salud y una asistencia financiera adecuada\".</p>",
"REF047"=>"<p><b>Directrices:</b> 132<br>
<b>Avanzando en la implementación:</b>  \"... Los niños con necesidades especiales, como discapacidades, deberían poder...\" Directrices 132<br>
<b>FCI:</b> Indicator 9, Page 17</p>",
"REF048"=>"<p><b>Directrices:</b> 60<br>
<b>Avanzando en la implementación:</b> \"... las Directrices indican que, tanto idealmente como en la realidad, una amplia gama de entornos de acogimiento informales y formales, sumada al retorno al hogar en los casos en los que sea posible, pueden constituir soluciones posibles para la 'permanencia' si cumplen con aquellas condiciones\" (pág. 75)<br>
<b>FCI:</b> Indicator 12, Page 20</p>",
"REF049"=>"<p><b>Directrices:</b> 56, 76-79<br>
<b>Avanzando en la implementación:</b> \"Los autores de las Directrices acordaron que había que marcar una clara distinción entre las responsabilidades del Estado en el caso de un entorno informal y aquellas en situaciones de 'acogimiento formal'” (pág. 79).</p>",
"REF050"=>"<p><b>Avanzando en la implementación:</b> \"... es deseable que el paradero de los niños sea conocido de los servicios competentes, a efectos de que puedan ofrecer la protección y el apoyo según se requiera\" (Avanzando en la implementación, pág. 79).</p>",
"REF051"=>"<p><b>Avanzando en la implementación:</b> \"Hay instancias en las que la formalización de una solución de acogimiento informal bien establecida y exitosa puede beneficiar a todos aquellos que se encuentran afectados. Las Directrices animan a los cuidadores informales a que consideren hacerlo si todas las partes están de acuerdo y si una acción como esta corresponde al interés superior del niño a más largo plazo (§ 56)\" (Avanzando en la implementación, pág. 79).</p>",
"REF052"=>"<p><b>Directrices:</b> 37<br>
<b>Avanzando en la implementación:</b> \"Las Directrices (...) se han inclinado a favor de posibilitar que los niños permanezcan como un hogar con sus derechos protegidos (§ 37). Por supuesto, esto depende de que la cabeza de familia sea capaz de cumplir ese papel y esté dispuesta a hacerlo\" (pág. 52).</p>",
"REF053"=>"<p><b>Directrices:</b> 105-117<br>
<b>Avanzando en la implementación:</b> Las Directrices (§105-117) proporcionan \"una revisión detallada de los requisitos generales esperados de los proveedores de cuidado, algunos de los cuales son mencionados previamente en las Directrices\" (pág. 90).</p>",
"REF054"=>"<p><b>Directrices:</b> 98, 99<br>
<b>Avanzando en la implementación:</b> \"...las Directrices reconocen la necesidad de los niños en modalidades alternativas de cuidado de poder manifestar preocupaciones relativas a su situación o tratamiento confiando en una persona de confianza, sin miedo a ser castigados (§ 98) y tener acceso a mecanismos efectivos de queja (§ 99). Los jóvenes con experiencia en las modalidades alternativas de cuidado deberían ser invitados a jugar un rol en el proceso de queja\" (pág. 82).</p>",
"REF055"=>"<p><b>Directrices:</b> 96, 97<br>
<b>Avanzando en la implementación:</b> \"Las Directrices recuerdan que el derecho internacional prohíbe el uso de la disciplina o del control del comportamiento que constituyan 'tortura o tratos crueles, inhumanos o degradantes' (§ 96). Además, las Directrices imponen restricciones severas en el uso de la fuerza y de la coerción (§ 97), así como la prohibición de cualquier tratamiento que pueda poner en peligro la salud física o mental de un niño\" (pág. 87).<br>
<b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF056"=>"<p><b>Directrices: </b>97. No se debería autorizar el uso de la fuerza ni de medidas de coerción de  cualquier tipo a menos que tales medidas sean estrictamente necesarias para salvaguardar la integridad física o psicológica del niño o de otras personas y se  apliquen de conformidad con la ley y de manera razonable y proporcionada y  respetando los derechos fundamentales del niño. La coerción mediante drogas y  medicación debería basarse en las necesidades terapéuticas y no se debería emplear  nunca sin la evaluación y prescripción de un especialista.<br>
<b>FCI:</b> Indicator 14, Page 22<br>
<br>
</p>",
"REF057"=>"<p><b>Directrices:</b> 71, 84, 87, 89, 90, 106, 107, 113-117<br>
<b>Avanzando en la implementación:</b> \"Las Directrices señalan la importancia de unas condiciones laborales positivas (§ 114) y de la formación apropiada del personal (§ 115), incluyendo la manera de hacer frente a un comportamiento desafiante (§ 116) y de responder a los niños con necesidades especiales (§ 117)\". V. \"El establecimiento de estándares para la contratación en los servicios y centros de acogimiento formal\" (pág. 91).</p>",
"REF058"=>"<p><b>FCI:</b> Indicador 11, pág. 19</p>",
"REF059"=>"<p><b>Directrices:</b> 126<br>
\"Los Estados deberían velar por que los entornos de acogimiento residencial dispongan de cuidadores suficientes para que el niño reciba una atención personalizada y, si corresponde, para dar al niño la oportunidad de crear vínculos con un cuidador determinado. Los cuidadores también deberían estar distribuidos en el entorno de acogimiento de tal modo que se alcancen efectivamente sus fines y objetivos y se logre la protección del niño\".</p>",
"REF060"=>"<p><b>Directrices:</b> 20, 55, 71, 73, 105, 128, 129<br>
<b>Avanzando en la implementación:</b> Las Directrices han prestado \"una atención particular al enfatizar los requisitos para la autorización e inspección\" (pág. 111);<br>
V. \"El desarrollo de sistemas fiables y responsables de  autorización e inspección\" (pág. 111).</p>",
"REF061"=>"<p><b>Directrices:</b> 55, 105<br>
<b>Avanzando en la implementación:</b> \"La autorización de todas  las entidades y personas que prestan acogimiento debería  ser concedida por 'servicios de asistencia social u otra  autoridad competente' (§105) con base en un conjunto establecido de criterios para evaluar la idoneidad del  proveedor para funcionar (§ 55)\" (pág. 109).<br>
<b>FCI:</b> Indicador 15, pág. 23</p>",
"REF062"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF063"=>"<p><b>Directrices:</b> 55, 105, 128, 129<br>
<b>Avanzando en la implementación:</b> \"Inspección: cada autorización inicial para prestar acogimiento alternativo está sujeta a 'la revisión y el control regulares' por parte de la autoridad competente\" (pág. 111).</p>",
"REF064"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF065"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF066"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF067"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF068"=>"<p><b>FCI:</b> Indicator 14, Page 22</p>",
"REF069"=>"<p><b>FCI:</b> Indicador 15, pág. 23</p>",
"REF070"=>"<p><b>Avanzando en la implementación:</b> Además de reunir las normas mínimas generales, el entorno de cuidado seleccionado deberá ser aquel que mejor responda a las necesidades del niño en el momento dado. \"También implica que una variedad de entornos de cuidado en un ámbito familiar u otros entornos deba establecerse, a efectos de que exista una verdadera selección y que exista un procedimiento reconocido y sistemático para determinar cuál es el más adecuado ('prevención del ingreso a las modalidades alternativas de cuidado')\" (pág. 23).</p>",
"REF071"=>"<p><b>Avanzando en la implementación:</b> \"La recolección nacional y el análisis de datos y de información sólida es esencial para desarrollar un enfoque basado en evidencia respecto del desarrollo de políticas y servicios\" (pág. 81)<br>
<b>FCI:</b> Indicador 4 (central), pág. 12</p>",
"REF072"=>"<p><b>Directrices:</b> 53, 54, 69, 75, 76, 118-122<br>
<b>Avanzando en la implementación:</b> \"En la gama de opciones de acogimiento alternativo exigidas para garantizar la disponibilidad de entornos de cuidado que puedan responder a las distintas necesidades y circunstancias de cada niño (§ 54), la prioridad debería darse a la promoción de 'soluciones basadas en la familia y la comunidad' (§ 53). Estas pueden ser formales, tradicionales o informales (§69, 75, 76)\" (págs. 93-94).</p>",
"REF073"=>"<p><b>FCI:</b> Indicador 4 (central), pág. 12</p>",
"REF074"=>"<p><b>FCI:</b> Indicador 2 (central), pág. 10</p>",
"REF075"=>"<p><b>FCI:</b> Indicador 1 (central), pág. 9</p>",
"REF076"=>"<p><b>Avanzando en la implementación:</b> &nbsp;\"Con respecto a los requisitos con los que deben cumplir los proveedores de acogimiento residencial, las Directrices estipulan que los centros de acogida deberían ser pequeños, y organizarse para parecerse lo más posible a un entorno familiar o a un grupo reducido\" (pág. 96).</p>",
"REF077"=>"<p><b>FCI:</b> Indicador 2 (central), pág. 10</p>",
"REF078"=>"<p>FCI: FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF079"=>"<p><b>Directrices:</b> 22<br>
<b>Avanzando en la implementación:</b> Las Directrices (§2) enfatizan el hecho de que los niños menores de 3 años deben ubicarse en entornos familiares, reconociendo que podrían existir algunas excepciones para acogimientos a corto plazo. Ver \"El acogimiento de niños de 0 a 3 años de edad en ámbitos familiares\" e \"Implicancias para la elaboración de políticas\" (págs. 40-42).</p>",
"REF080"=>"<p><b>Directrices:</b> 21, 23, 123-127<br>
<b>Avanzando en la implementación:</b> \"... los autores de las Directrices optaron, en el §23, por apelar a cada Estado a que elabore su propia estrategia para la desinstitucionalización gradual de sus sistemas de modalidades alternativas de cuidado, en lugar de proponer una prohibición rotunda de las instituciones\". Ver \"Las estrategias para la desinstitucionalización de los sistemas de modalidades alternativas de cuidado\" e \"Implicancias para la elaboración de políticas\" (Avanzando en la implementación, págs. 44-49).</p>",
"REF081"=>"<p><b>FCI:</b> Indicador 2 (central), pág. 10; indicador 4 (central), pág. 12</p>",
"REF082"=>"<p><b>Directrices:</b> 137-152<br>
<b>Avanzando en la implementación:</b> \"Las Directrices utilizan el término 'país de residencia habitual' (§ 137, 140) para garantizar que el criterio de aplicación de disposiciones se fundamente en el lugar en el que el niño ha vivido de hasta la fecha\" (pág. 116).&nbsp; <br>
Ver \"Implicancias para la elaboración de políticas: La prestación de acogimiento a los niños fuera de su país de residencia habitual\" (pág. 118).</p>",
"REF083"=>"<p><b>Directrices:</b> 140-152<br>
<b>Avanzando en la implementación:</b> \"A diferencia de la prestación de acogimiento formal o informal planeado en el extranjero, esta sub-sección (§ 140-152) trata de la necesidad más común de asegurar el acogimiento alternativo de un niño no acompañado o separado que se encuentra fuera de su país de residencia habitual. Incluye a los niños en una amplia gama de situaciones, incluyendo a los refugiados y solicitantes de asilo, los migrantes en situación irregular, y las víctimas de trata, sustracción y otras formas de migración forzada\" (pág. 117).</p>",
"REF084"=>"<p><b>Directrices:</b> 142<br>
<b>Avanzando en la implementación:</b> \"Las Directrices exigen que la prestación de modalidades alternativas de cuidado en estos casos tome en cuenta las características y la experiencia individual de cada niño (§ 142)\" (pág. 117).</p>",
"REF085"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF086"=>"<p><b>Directrices:</b> 153-167<br>
<b>Avanzando en la implementación:</b> \"Mientras que las Directrices en su conjunto son aplicables en situaciones de desastre natural o causado por el hombre (§ 153), se deben tratar algunas preocupaciones relativas al acogimiento alternativo de los niños en estas circunstancias\".<br>
Ver \"Brindar acogimiento alternativo en situaciones de emergencia\" (pág. 119).</p>",
"REF087"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF088"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF089"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF090"=>"<p><b>FCI:</b> FCI:&nbsp;Indicador 13, pág. 21</p>",
"REF091"=>"<p><b>Directrices:</b> 96. Todas las medidas disciplinarias y de control del comportamiento que  constituyan tortura o tratos crueles, inhumanos o degradantes, incluidas las medidas  de aislamiento e incomunicación o cualesquiera otras formas de violencia física o  psicológica que puedan poner en peligro la salud física o mental del niño, deben quedar prohibidas estrictamente de conformidad con las normas internacionales de  derechos humanos. Los Estados deben adoptar todas las medidas necesarias para  impedir tales prácticas y garantizar su punibilidad conforme al derecho. Nunca  debería imponerse como sanción restringir el contacto del niño con los miembros de  su familia y con otras personas de importancia especial para él.</p>",
"REF092"=>"<p><b>Directrices: </b>100. Para promover en el niño el sentido de la propia identidad, debería llevarse,  con la participación de este, un diario  e vida que contenga la información relativa a  cada etapa de la vida del niño, junto con las fotografías, los objetos personales y los  recuerdos correspondientes, para que el niño pudiera disponer de él durante toda su  vida.</p>",
);